### ISSUE TITLE
php artisan migrate giving errors

### ISSUE THREAD

**Issue by flik** [ferdousulhaque/laratrust-adminpanel#2]
dev@ubuntu:/var/www/app/server$ php artisan migrate

In Connection.php line 664:

  could not find driver (SQL: select * from information_schema.tables where table_schema = xxx and table_name = migrations)

In Connector.php line 67:

  could not find driver

**Comment by flik** [comment]
I have fixed this issue with:

I have to enable mysql and pdo extentions in my linux server then after restart apache
I executed commands: 
```
php artisan key:generate
php artisan config:clear
php artisan config:cache
```
Then everything fixed:

**Comment by ferdousulhaque** [comment]
Actually I have mentioned the steps for configuration in the README.md. Thanks.
